/**
 * AI platform definitions with detection URLs and region rules.
 * Region rules use ISO 3166-1 alpha-2 country codes.
 */

const OPENAI_SUPPORTED = new Set([
  'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ', 'BS', 'BD', 'BB', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA', 'BW', 'BR', 'BN', 'BG', 'BF', 'CV', 'CA', 'CL', 'CO', 'KM', 'CG', 'CR', 'CI', 'HR', 'CY', 'CZ', 'DK', 'DJ', 'DM', 'DO', 'EC', 'SV', 'EE', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR', 'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'VA', 'HN', 'HU', 'IS', 'IN', 'ID', 'IQ', 'IE', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KW', 'KG', 'LV', 'LB', 'LS', 'LR', 'LI', 'LT', 'LU', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NA', 'NR', 'NP', 'NL', 'NZ', 'NI', 'NE', 'NG', 'MK', 'NO', 'OM', 'PK', 'PW', 'PS', 'PA', 'PG', 'PY', 'PE', 'PH', 'PL', 'PT', 'QA', 'RW', 'KN', 'LC', 'VC', 'WS', 'SM', 'ST', 'SN', 'RS', 'SC', 'SL', 'SG', 'SK', 'SI', 'SB', 'ZA', 'KR', 'ES', 'LK', 'SR', 'SE', 'CH', 'TW', 'TZ', 'TH', 'TL', 'TG', 'TO', 'TT', 'TN', 'TR', 'TV', 'UG', 'UA', 'AE', 'GB', 'US', 'UY', 'VU', 'ZM', 'XX', 'T1'
]);

const ANTHROPIC_BLOCKED = new Set(['CN', 'HK', 'MO']);

const PLATFORMS = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    icon: '🤖',
    url: 'https://chatgpt.com',
    checkUrl: 'https://chatgpt.com/cdn-cgi/trace',
    regionCheck: (cc) => OPENAI_SUPPORTED.has(cc),
  },
  {
    id: 'claude',
    name: 'Claude',
    icon: '🟠',
    url: 'https://claude.ai',
    checkUrl: 'https://claude.ai',
    regionCheck: (cc) => !ANTHROPIC_BLOCKED.has(cc),
  },
  {
    id: 'gemini',
    name: 'Gemini',
    icon: '✨',
    url: 'https://gemini.google.com',
    checkUrl: 'https://gemini.google.com',
    regionCheck: (cc) => !['CN', 'IR', 'KP', 'SY', 'CU'].includes(cc),
  },
  {
    id: 'google-aimode',
    name: 'Google AI Mode',
    icon: '🧠',
    url: 'https://www.google.com/aimode',
    checkUrl: 'https://www.google.com/aimode',
    regionCheck: (cc) => !['CN', 'IR', 'KP', 'SY', 'CU'].includes(cc),
  },
  {
    id: 'copilot',
    name: 'Copilot',
    icon: '🔵',
    url: 'https://copilot.microsoft.com',
    checkUrl: 'https://copilot.microsoft.com',
    regionCheck: (cc) => !['CN', 'RU', 'BY', 'KP', 'IR', 'CU'].includes(cc),
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    icon: '🔍',
    url: 'https://www.perplexity.ai',
    checkUrl: 'https://www.perplexity.ai',
    regionCheck: (cc) => !['CN', 'RU', 'IR', 'KP', 'CU'].includes(cc),
  },
  {
    id: 'grok',
    name: 'Grok',
    icon: '⚡',
    url: 'https://grok.com',
    checkUrl: 'https://grok.com',
    regionCheck: (cc) => !['CN', 'RU', 'IR', 'KP', 'CU', 'BY'].includes(cc),
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    icon: '🌬️',
    url: 'https://chat.mistral.ai',
    checkUrl: 'https://chat.mistral.ai',
    regionCheck: () => true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: '🐋',
    url: 'https://chat.deepseek.com',
    checkUrl: 'https://chat.deepseek.com',
    regionCheck: () => true,
  },
  {
    id: 'poe',
    name: 'Poe',
    icon: '📝',
    url: 'https://poe.com',
    checkUrl: 'https://poe.com',
    regionCheck: (cc) => OPENAI_SUPPORTED.has(cc),
  },
  {
    id: 'character',
    name: 'Character.AI',
    icon: '🎭',
    url: 'https://character.ai',
    checkUrl: 'https://character.ai',
    regionCheck: (cc) => !['CN', 'RU', 'CU', 'IR', 'KP'].includes(cc),
  },
  {
    id: 'huggingface',
    name: 'HuggingChat',
    icon: '🤗',
    url: 'https://huggingface.co',
    checkUrl: 'https://huggingface.co',
    regionCheck: () => true,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    icon: '🔗',
    url: 'https://cohere.com',
    checkUrl: 'https://cohere.com',
    regionCheck: () => true,
  },
  {
    id: 'meta',
    name: 'Meta AI',
    icon: '🦙',
    url: 'https://www.meta.ai',
    checkUrl: 'https://www.meta.ai',
    regionCheck: (cc) => !['CN', 'RU', 'IR', 'KP', 'CU'].includes(cc),
  },
  {
    id: 'pi',
    name: 'Pi',
    icon: '🥧',
    url: 'https://pi.ai',
    checkUrl: 'https://pi.ai',
    regionCheck: (cc) => !['CN', 'RU', 'IR', 'KP', 'CU'].includes(cc),
  },
  {
    id: 'you',
    name: 'You.com',
    icon: '🎯',
    url: 'https://you.com',
    checkUrl: 'https://you.com',
    regionCheck: (cc) => !['CN', 'RU', 'IR', 'KP', 'CU'].includes(cc),
  },
  {
    id: 'phind',
    name: 'Phind',
    icon: '💻',
    url: 'https://phind.com',
    checkUrl: 'https://phind.com',
    regionCheck: () => true,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    icon: '🔁',
    url: 'https://replicate.com',
    checkUrl: 'https://replicate.com',
    regionCheck: () => true,
  },
  {
    id: 'together',
    name: 'Together AI',
    icon: '🤝',
    url: 'https://www.together.ai',
    checkUrl: 'https://www.together.ai',
    regionCheck: () => true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: '🛣️',
    url: 'https://openrouter.ai',
    checkUrl: 'https://openrouter.ai',
    regionCheck: () => true,
  },
  {
    id: 'stability',
    name: 'Stability AI',
    icon: '🎨',
    url: 'https://stability.ai',
    checkUrl: 'https://stability.ai',
    regionCheck: () => true,
  },
  {
    id: 'kimi',
    name: 'Kimi',
    icon: '🌙',
    url: 'https://www.kimi.com',
    checkUrl: 'https://www.kimi.com',
    regionCheck: () => true,
  },
  {
    id: 'qwen',
    name: 'Qwen Chat',
    icon: '🐱',
    url: 'https://chat.qwen.ai',
    checkUrl: 'https://chat.qwen.ai',
    regionCheck: () => true,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    icon: '🖱️',
    url: 'https://cursor.com',
    checkUrl: 'https://cursor.com',
    regionCheck: (cc) => !['CN', 'IR', 'KP', 'CU'].includes(cc),
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    icon: '🖼️',
    url: 'https://www.midjourney.com/home',
    checkUrl: 'https://www.midjourney.com/home',
    regionCheck: (cc) => !['CN', 'RU', 'IR', 'KP', 'CU'].includes(cc),
  },
  {
    id: 'aistudio',
    name: 'Google AI Studio',
    icon: '🧪',
    url: 'https://aistudio.google.com',
    checkUrl: 'https://aistudio.google.com',
    regionCheck: (cc) => !['CN', 'IR', 'KP', 'SY', 'CU'].includes(cc),
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    icon: '📓',
    url: 'https://notebooklm.google.com',
    checkUrl: 'https://notebooklm.google.com',
    regionCheck: (cc) => !['CN', 'IR', 'KP', 'SY', 'CU'].includes(cc),
  },
  {
    id: 'groq',
    name: 'Groq',
    icon: '⚙️',
    url: 'https://groq.com',
    checkUrl: 'https://groq.com',
    regionCheck: () => true,
  },
  {
    id: 'runway',
    name: 'Runway',
    icon: '🎬',
    url: 'https://runwayml.com',
    checkUrl: 'https://runwayml.com',
    regionCheck: (cc) => !['CN', 'RU', 'IR', 'KP', 'CU'].includes(cc),
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    icon: '🎙️',
    url: 'https://elevenlabs.io',
    checkUrl: 'https://elevenlabs.io',
    regionCheck: () => true,
  },
];

module.exports = { PLATFORMS, OPENAI_SUPPORTED };
